name: flutter_vault
description: Flutter application which contains anything and everything.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  rxdart: ^0.22.6
  http: ^0.12.0+2
  sqflite: ^1.1.7+3
  path_provider: ^1.4.4
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image_01.png
    - assets/image_02.png
    - assets/logo.png
    - assets/logo2.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf